#Password Manager
cask "1password"

#Code and text editor
cask "visual-studio-code"

#Socials
cask "discord"
cask "slack"

#Browsers
cask "firefox"
cask "google-chrome"

#Temp and throttling utility
cask "hot"